version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- choco install opencover.portable
- choco install codecov
- cmd: dotnet restore ./src/Ametista.sln
build:
  project: ./src/Ametista.sln
  verbosity: minimal
test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Ametista.UnitTest\bin\Debug\Ametista.UnitTest.dll -noshadow" -filter:"+[Ametista.*]* -[Ametista.UnitTest*]*" -output:".\Ametista_UnitTest.xml" -oldstyle
- codecov -f "Ametista_UnitTest.xml
